// <auto-generated />
using System;
using GestaoEscolar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoEscolar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231025001849_relacaoDeptoInst")]
    partial class relacaoDeptoInst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoEscolar.Models.Departamento", b =>
                {
                    b.Property<long>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DepartamentoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("fk_InstituicaoId")
                        .HasColumnType("bigint");

                    b.HasKey("DepartamentoId");

                    b.HasIndex("fk_InstituicaoId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Instituicao", b =>
                {
                    b.Property<long?>("InstituicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("InstituicaoId"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InstituicaoId");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Departamento", b =>
                {
                    b.HasOne("GestaoEscolar.Models.Instituicao", "Instituicao")
                        .WithMany("Departamentos")
                        .HasForeignKey("fk_InstituicaoId");

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("GestaoEscolar.Models.Instituicao", b =>
                {
                    b.Navigation("Departamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
